AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudFormationQuotas:
    Type: 'OC::ServiceQuotas::CloudFormationQuotas'
    Properties:
      Stacks: 200
      ResourceTypes: 100
      VersionsPerResourceType: 100