AWSTemplateFormatVersion: 2010-09-09
Resources:
  OlafOU:
    Type: 'Community::Organizations::OrganizationalUnit'
    Properties:
      OrganizationalUnitName: 'Olaf'
  
  ChildOU:
    Type: 'Community::Organizations::OrganizationalUnit'
    Properties:
      OrganizationalUnitName: 'Child'
      ParentOU: !GetAtt OlafOU.Id

  Child2OU:
    Type: 'Community::Organizations::OrganizationalUnit'
    Properties:
      OrganizationalUnitName: 'Child2'
      ParentOU: !GetAtt OlafOU.Id

  ChildChildOU:
    Type: 'Community::Organizations::OrganizationalUnit'
    Properties:
      OrganizationalUnitName: 'Child'
      ParentOU: !GetAtt OlafOU.Id

  Account1:
    Type: 'Community::Organizations::Account'
    Properties:
      ParentOU: !GetAtt OlafOU.Id
      AccountName: Production 1 Account
      RootEmail: production1@olafconijn.awsapps.com
      Alias: my-production1
      SupportLevel: 'enterprise'
 

  # ServiceControlPolicy:
  #   Type: 'Community::Organizations::ServiceControlPolicy'
  #   Properties:
  #     PolicyName: RestrictUnusedRegions
  #     Description: Restrict Unused regions
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Sid: DenyUnsupportedRegions
  #           Effect: Deny
  #           NotAction:
  #             - 'cloudfront:*'
  #             - 'iam:*'
  #             - 'route53:*'
  #             - 'support:*'
  #             - 'budgets:*'
  #           Resource: '*'
  #           Condition:
  #             StringNotEquals:
  #               'aws:RequestedRegion':
  #                 - eu-west-1
  #                 - us-east-1
  #                 - eu-central-1